version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: flowapp-mailhog
      ports:
        - "8025:8025"

    mysql:
      image: mysql:5.7
      container_name: flowapp-mysql
      user: "1000:50"
      volumes:
        - ./_mysql/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=admin
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=pass
      ports:
       - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: flowapp-webserver
      volumes:
          - flowappweb-sync:/application:rw
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: php-fpm
      container_name: flowapp-php-fpm
      volumes:
        - flowappweb-sync:/application:rw
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
volumes:
  flowappweb-sync:
    external: true

